name: facebook
favicon: null
layout_spectrum: 0.5405416386201978
typography_spectrum: 0.24775928701274097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4136084367055446
  lightness: 0.86842898465693
  saturation: 0.8172399953473359
  rhythmicContrast: 0.49003222421742976
purpose: []
